<?php
## FILE GENERATED BY MAGRATHEA.
## This file was automatically generated and changes can be overwritten through the admin
## -- date of creation: [2025-09-20 02:43:17]

namespace MagratheaContacts\Mailpromises\Base;

use Magrathea2\MagratheaModelControl;

class MailpromisesControlBase extends MagratheaModelControl {
	protected static $modelNamespace = "MagratheaContacts\Mailpromises";
	protected static $modelName = "Mailpromises";
	protected static $dbTable = "mail_promises";
}
