<?php
## FILE GENERATED BY MAGRATHEA.
## This file was automatically generated and changes can be overwritten through the admin
## -- date of creation: [2025-09-20 02:43:16]

namespace MagratheaContacts\Mailpromises\Base;

use Magrathea2\iMagratheaModel;
use Magrathea2\MagratheaModel;

class MailpromisesBase extends MagratheaModel implements iMagratheaModel {

	public $id, $source_id, $origin_key, $mail_type, $email_from, $email_replyTo, $email_to, $priority, $vars, $template_id, $mail_id, $processed, $processed_date;
	public $created_at, $updated_at;
	protected $autoload = null;

	public function __construct(  $id=0  ){ 
		$this->MagratheaStart();
		if( !empty($id) ){
			$pk = $this->dbPk;
			$this->$pk = $id;
			$this->GetById($id);
		}
	}
	public function MagratheaStart(){
		$this->dbTable = "mail_promises";
		$this->dbPk = "id";
		$this->dbValues["id"] = "int";
		$this->dbValues["source_id"] = "int";
		$this->dbValues["origin_key"] = "string";
		$this->dbValues["mail_type"] = "string";
		$this->dbValues["email_from"] = "string";
		$this->dbValues["email_replyTo"] = "string";
		$this->dbValues["email_to"] = "string";
		$this->dbValues["priority"] = "int";
		$this->dbValues["vars"] = "text";
		$this->dbValues["template_id"] = "int";
		$this->dbValues["mail_id"] = "int";
		$this->dbValues["processed"] = "boolean";
		$this->dbValues["processed_date"] = "datetime";
		$this->dbValues["created_at"] =  "datetime";
		$this->dbValues["updated_at"] =  "datetime";

		$this->relations["properties"]["Source"] = null;
		$this->relations["methods"]["Source"] = "GetSource";
		$this->relations["lazyload"]["Source"] = "true";
		$this->relations["external"]["source_id"] = "\MagratheaContacts\Source\Source";
		$this->relations["properties"]["Templates"] = null;
		$this->relations["methods"]["Templates"] = "GetTemplates";
		$this->relations["lazyload"]["Templates"] = "true";
		$this->relations["external"]["template_id"] = "\MagratheaContacts\Templates\Templates";

	}

	public function GetControl() {
		return new \MagratheaContacts\Mailpromises\Base\MailpromisesControlBase();
	}

	// >>> relations:
	public function GetSource(){
		if($this->relations["properties"]["Source"] != null) return $this->relations["properties"]["Source"];
		$this->relations["properties"]["Source"] = new \MagratheaContacts\Source\Source($this->source_id);
		return $this->relations["properties"]["Source"];
	}
	public function SetSource($source){
		$this->relations["properties"]["Source"] = $source;
		$this->source_id = $source->GetID();
		return $this;
	}
	public function GetTemplates(){
		if($this->relations["properties"]["Templates"] != null) return $this->relations["properties"]["Templates"];
		$this->relations["properties"]["Templates"] = new \MagratheaContacts\Templates\Templates($this->template_id);
		return $this->relations["properties"]["Templates"];
	}
	public function SetTemplates($templates){
		$this->relations["properties"]["Templates"] = $templates;
		$this->template_id = $templates->GetID();
		return $this;
	}

}
