<?php
## FILE GENERATED BY MAGRATHEA.
## This file was automatically generated and changes can be overwritten through the admin
## -- date of creation: [2025-09-20 02:43:00]

namespace MagratheaContacts\Templates\Base;

use Magrathea2\MagratheaModelControl;

class TemplatesControlBase extends MagratheaModelControl {
	protected static $modelNamespace = "MagratheaContacts\Templates";
	protected static $modelName = "Templates";
	protected static $dbTable = "templates";
}
