<?php
## FILE GENERATED BY MAGRATHEA.
## This file was automatically generated and changes can be overwritten through the admin
## -- date of creation: [2025-09-20 02:42:59]

namespace MagratheaContacts\Templates\Base;

use Magrathea2\iMagratheaModel;
use Magrathea2\MagratheaModel;

class TemplatesBase extends MagratheaModel implements iMagratheaModel {

	public $id, $name, $source_id, $description, $msg_subject, $content, $vars, $active;
	public $created_at, $updated_at;
	protected $autoload = null;

	public function __construct(  $id=0  ){ 
		$this->MagratheaStart();
		if( !empty($id) ){
			$pk = $this->dbPk;
			$this->$pk = $id;
			$this->GetById($id);
		}
	}
	public function MagratheaStart(){
		$this->dbTable = "templates";
		$this->dbPk = "id";
		$this->dbValues["id"] = "int";
		$this->dbValues["name"] = "string";
		$this->dbValues["source_id"] = "int";
		$this->dbValues["description"] = "string";
		$this->dbValues["msg_subject"] = "string";
		$this->dbValues["content"] = "text";
		$this->dbValues["vars"] = "text";
		$this->dbValues["active"] = "boolean";
		$this->dbValues["created_at"] =  "datetime";
		$this->dbValues["updated_at"] =  "datetime";

		$this->relations["properties"]["Source"] = null;
		$this->relations["methods"]["Source"] = "GetSource";
		$this->relations["lazyload"]["Source"] = "true";
		$this->relations["external"]["source_id"] = "\MagratheaContacts\Source\Source";
		$this->relations["properties"]["Mailpromisess"] = null;
		$this->relations["methods"]["Mailpromisess"] = "GetMailpromisess";
		$this->relations["lazyload"]["Mailpromisess"] = "true";

	}

	public function GetControl() {
		return new \MagratheaContacts\Templates\Base\TemplatesControlBase();
	}

	// >>> relations:
	public function GetSource(){
		if($this->relations["properties"]["Source"] != null) return $this->relations["properties"]["Source"];
		$this->relations["properties"]["Source"] = new \MagratheaContacts\Source\Source($this->source_id);
		return $this->relations["properties"]["Source"];
	}
	public function SetSource($source){
		$this->relations["properties"]["Source"] = $source;
		$this->source_id = $source->GetID();
		return $this;
	}
	public function GetMailpromisess(){
		if($this->relations["properties"]["Mailpromisess"] != null) return $this->relations["properties"]["Mailpromisess"];
		$pk = $this->dbPk;
		$this->relations["properties"]["Mailpromisess"] = \MagratheaContacts\Mailpromises\Base\MailpromisesControlBase::GetWhere(array("template_id" => $this->$pk));
		return $this->relations["properties"]["Mailpromisess"];
	}

}
