<?php
## FILE GENERATED BY MAGRATHEA.
## This file was automatically generated and changes can be overwritten through the admin
## -- date of creation: [2023-12-04 00:43:20]

namespace MagratheaContacts\Smtp\Base;

use Magrathea2\MagratheaModelControl;

class SmtpControlBase extends MagratheaModelControl {
	protected static $modelNamespace = "MagratheaContacts\Smtp";
	protected static $modelName = "Smtp";
	protected static $dbTable = "smtp";
}
