<?php
## FILE GENERATED BY MAGRATHEA.
## This file was automatically generated and changes can be overwritten through the admin
## -- date of creation: [2023-08-09 18:17:49]

namespace MagratheaContacts\Source;

use Magrathea2\iMagratheaModel;
use Magrathea2\MagratheaModel;

class SourceBase extends MagratheaModel implements iMagratheaModel {

	public $id, $name, $mail_from;
	public $created_at, $updated_at;
	protected $autoload = null;

	public function __construct(  $id=0  ){ 
		$this->MagratheaStart();
		if( !empty($id) ){
			$pk = $this->dbPk;
			$this->$pk = $id;
			$this->GetById($id);
		}
	}
	public function MagratheaStart(){
		$this->dbTable = "source";
		$this->dbPk = "id";
		$this->dbValues["id"] = "int";
		$this->dbValues["name"] = "string";
		$this->dbValues["mail_from"] = "string";
		$this->dbAlias["from"] = "mail_from";

		$this->relations["properties"]["Emails"] = null;
		$this->relations["methods"]["Emails"] = "GetEmails";
		$this->relations["lazyload"]["Emails"] = "true";
		$this->relations["properties"]["Apikeys"] = null;
		$this->relations["methods"]["Apikeys"] = "GetApikeys";
		$this->relations["lazyload"]["Apikeys"] = "true";
		$this->dbValues["created_at"] =  "datetime";
		$this->dbValues["updated_at"] =  "datetime";

	}

	// >>> relations:
	public function GetEmails(){
		if($this->relations["properties"]["Emails"] != null) return $this->relations["properties"]["Emails"];
		$pk = $this->dbPk;
		$this->relations["properties"]["Emails"] = EmailControlBase::GetWhere(array("source_id" => $this->$pk));
		return $this->relations["properties"]["Emails"];
	}
	public function GetApikeys(){
		if($this->relations["properties"]["Apikeys"] != null) return $this->relations["properties"]["Apikeys"];
		$pk = $this->dbPk;
		$this->relations["properties"]["Apikeys"] = ApikeyControlBase::GetWhere(array("source_id" => $this->$pk));
		return $this->relations["properties"]["Apikeys"];
	}

}
