<?php
## FILE GENERATED BY MAGRATHEA.
## This file was automatically generated and changes can be overwritten through the admin
## -- date of creation: [2023-08-11 12:07:16]

namespace MagratheaContacts\Source;

use Magrathea2\MagratheaModelControl;

class SourceControlBase extends MagratheaModelControl {
	protected static $modelNamespace = "MagratheaContacts\Source";
	protected static $modelName = "Source";
	protected static $dbTable = "source";
}
