<?php
## FILE GENERATED BY MAGRATHEA.
## This file was automatically generated and changes can be overwritten through the admin
## -- date of creation: [2023-12-04 00:42:55]

namespace MagratheaContacts\Source\Base;

use Magrathea2\MagratheaModelControl;

class SourceControlBase extends MagratheaModelControl {
	protected static $modelNamespace = "MagratheaContacts\Source";
	protected static $modelName = "Source";
	protected static $dbTable = "source";
}
