<?php
## FILE GENERATED BY MAGRATHEA.
## This file was automatically generated and changes can be overwritten through the admin
## -- date of creation: [2023-12-04 04:15:08]

namespace MagratheaContacts\Source\Base;

use Magrathea2\iMagratheaModel;
use Magrathea2\MagratheaModel;

class SourceBase extends MagratheaModel implements iMagratheaModel {

	public $id, $name, $mail_from, $smtp_id;
	public $created_at, $updated_at;
	protected $autoload = null;

	public function __construct(  $id=0  ){ 
		$this->MagratheaStart();
		if( !empty($id) ){
			$pk = $this->dbPk;
			$this->$pk = $id;
			$this->GetById($id);
		}
	}
	public function MagratheaStart(){
		$this->dbTable = "source";
		$this->dbPk = "id";
		$this->dbValues["id"] = "int";
		$this->dbValues["name"] = "string";
		$this->dbValues["mail_from"] = "string";
		$this->dbAlias["from"] = "mail_from";
		$this->dbValues["smtp_id"] = "int";
		$this->dbValues["created_at"] =  "datetime";
		$this->dbValues["updated_at"] =  "datetime";

		$this->relations["properties"]["Emails"] = null;
		$this->relations["methods"]["Emails"] = "GetEmails";
		$this->relations["lazyload"]["Emails"] = "true";
		$this->relations["properties"]["Apikeys"] = null;
		$this->relations["methods"]["Apikeys"] = "GetApikeys";
		$this->relations["lazyload"]["Apikeys"] = "true";
		$this->relations["properties"]["Smtp"] = null;
		$this->relations["methods"]["Smtp"] = "GetSmtp";
		$this->relations["lazyload"]["Smtp"] = "true";
		$this->relations["external"]["smtp_id"] = "\MagratheaContacts\Smtp\Base\SmtpBase";

	}

	public function GetControl() {
		return new \MagratheaContacts\Source\Base\SourceControlBase();
	}

	// >>> relations:
	public function GetEmails(){
		if($this->relations["properties"]["Emails"] != null) return $this->relations["properties"]["Emails"];
		$pk = $this->dbPk;
		$this->relations["properties"]["Emails"] = \MagratheaContacts\Email\Base\EmailControlBase::GetWhere(array("source_id" => $this->$pk));
		return $this->relations["properties"]["Emails"];
	}
	public function GetApikeys(){
		if($this->relations["properties"]["Apikeys"] != null) return $this->relations["properties"]["Apikeys"];
		$pk = $this->dbPk;
		$this->relations["properties"]["Apikeys"] = \MagratheaContacts\Apikey\Base\ApikeyControlBase::GetWhere(array("source_id" => $this->$pk));
		return $this->relations["properties"]["Apikeys"];
	}
	public function GetSmtp(){
		if($this->relations["properties"]["Smtp"] != null) return $this->relations["properties"]["Smtp"];
		$this->relations["properties"]["Smtp"] = new \MagratheaContacts\Smtp\Base\SmtpBase($this->smtp_id);
		return $this->relations["properties"]["Smtp"];
	}
	public function SetSmtp($smtp){
		$this->relations["properties"]["Smtp"] = $smtp;
		$this->smtp_id = $smtp->GetID();
		return $this;
	}

}
