<?php
## FILE GENERATED BY MAGRATHEA.
## This file was automatically generated and changes can be overwritten through the admin
## -- date of creation: [2023-08-16 07:32:43]

namespace MagratheaContacts\Apikey;

use Magrathea2\MagratheaModelControl;

class ApikeyControlBase extends MagratheaModelControl {
	protected static $modelNamespace = "MagratheaContacts\Apikey";
	protected static $modelName = "Apikey";
	protected static $dbTable = "apikey";
}
