<?php
## FILE GENERATED BY MAGRATHEA.
## This file was automatically generated and changes can be overwritten through the admin
## -- date of creation: [2023-12-12 02:48:01]

namespace MagratheaContacts\Apikey\Base;

use Magrathea2\iMagratheaModel;
use Magrathea2\MagratheaModel;

class ApikeyBase extends MagratheaModel implements iMagratheaModel {

	public $id, $source_id, $description, $priority, $val, $uses, $usage_limit, $expiration, $simulate, $active;
	public $created_at, $updated_at;
	protected $autoload = array("Source" => ["obj" => "\MagratheaContacts\Source\Base\SourceBase","field" => "source_id"]);
	public $Source;

	public function __construct(  $id=0  ){ 
		$this->MagratheaStart();
		if( !empty($id) ){
			$pk = $this->dbPk;
			$this->$pk = $id;
			$this->GetById($id);
		}
	}
	public function MagratheaStart(){
		$this->dbTable = "apikey";
		$this->dbPk = "id";
		$this->dbValues["id"] = "int";
		$this->dbValues["source_id"] = "int";
		$this->dbValues["description"] = "string";
		$this->dbValues["priority"] = "int";
		$this->dbValues["val"] = "string";
		$this->dbValues["uses"] = "int";
		$this->dbValues["usage_limit"] = "int";
		$this->dbAlias["usage"] = "usage_limit";
		$this->dbValues["expiration"] = "datetime";
		$this->dbValues["simulate"] = "boolean";
		$this->dbValues["active"] = "boolean";
		$this->dbValues["created_at"] =  "datetime";
		$this->dbValues["updated_at"] =  "datetime";

		$this->relations["properties"]["Source"] = null;
		$this->relations["methods"]["Source"] = "GetSource";
		$this->relations["lazyload"]["Source"] = "true";
		$this->relations["external"]["source_id"] = "\MagratheaContacts\Source\Base\SourceBase";

	}

	public function GetControl() {
		return new \MagratheaContacts\Apikey\Base\ApikeyControlBase();
	}

	// >>> relations:
	public function GetSource(){
		if($this->relations["properties"]["Source"] != null) return $this->relations["properties"]["Source"];
		$this->relations["properties"]["Source"] = new \MagratheaContacts\Source\Base\SourceBase($this->source_id);
		return $this->relations["properties"]["Source"];
	}
	public function SetSource($source){
		$this->relations["properties"]["Source"] = $source;
		$this->source_id = $source->GetID();
		return $this;
	}

}
