<?php
## FILE GENERATED BY MAGRATHEA.
## This file was automatically generated and changes can be overwritten through the admin
## -- date of creation: [2023-12-04 00:43:07]

namespace MagratheaContacts\Apikey\Base;

use Magrathea2\MagratheaModelControl;

class ApikeyControlBase extends MagratheaModelControl {
	protected static $modelNamespace = "MagratheaContacts\Apikey";
	protected static $modelName = "Apikey";
	protected static $dbTable = "apikey";
}
