<?php
## FILE GENERATED BY MAGRATHEA.
## This file was automatically generated and changes can be overwritten through the admin
## -- date of creation: [2023-11-27 00:13:55]

namespace MagratheaContacts\Email\Base;

use Magrathea2\MagratheaModelControl;

class EmailControlBase extends MagratheaModelControl {
	protected static $modelNamespace = "MagratheaContacts\Email";
	protected static $modelName = "Email";
	protected static $dbTable = "mail";
}
