<?php
## FILE GENERATED BY MAGRATHEA.
## This file was automatically generated and changes can be overwritten through the admin
## -- date of creation: [2024-11-04 17:45:02]

namespace MagratheaContacts\Cronlogs\Base;

use Magrathea2\iMagratheaModel;
use Magrathea2\MagratheaModel;

class CronlogsBase extends MagratheaModel implements iMagratheaModel {

	public $id, $timestart, $timeend, $status, $result, $log;
	public $created_at, $updated_at;
	protected $autoload = null;

	public function __construct(  $id=0  ){ 
		$this->MagratheaStart();
		if( !empty($id) ){
			$pk = $this->dbPk;
			$this->$pk = $id;
			$this->GetById($id);
		}
	}
	public function MagratheaStart(){
		$this->dbTable = "cronlogs";
		$this->dbPk = "id";
		$this->dbValues["id"] = "int";
		$this->dbValues["timestart"] = "datetime";
		$this->dbValues["timeend"] = "datetime";
		$this->dbValues["status"] = "string";
		$this->dbValues["result"] = "string";
		$this->dbValues["log"] = "text";
		$this->dbValues["created_at"] =  "datetime";
		$this->dbValues["updated_at"] =  "datetime";


	}

	public function GetControl() {
		return new \MagratheaContacts\Cronlogs\Base\CronlogsControlBase();
	}

	// >>> relations:

}
