<?php
## FILE GENERATED BY MAGRATHEA.
## This file was automatically generated and changes can be overwritten through the admin
## -- date of creation: [2024-11-04 16:47:02]

namespace MagratheaContacts\Cronlogs\Base;

use Magrathea2\MagratheaModelControl;

class CronlogsControlBase extends MagratheaModelControl {
	protected static $modelNamespace = "MagratheaContacts\Cronlogs";
	protected static $modelName = "Cronlogs";
	protected static $dbTable = "cronlogs";
}
