


on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy

    steps:
    - uses: actions/checkout@v3

    - name: Versioning
      run: bash build.sh

    - name: Validate composer.json and composer.lock on src dir
      run: composer validate --strict --working-dir=./src

    - name: Cache Composer packages
      if: always()
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: src/vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --working-dir=./src

  deployment:
    needs: build
    runs-on: ubuntu-latest
    name: Deployment Job
    steps:
    - uses: actions/checkout@v3

    - name: SSH ${{ vars.HOST }}
      uses: ErenKrt/ssh-push@main
      with:
        host: ${{ vars.HOST }}
        username: ${{ vars.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        source: "./src"
        destination: "$REMOTE_PROD/src"
        scripts: |
          cp $REMOTE_PROD/magrathea.conf $REMOTE_PROD/src/configs
