<?php
## FILE GENERATED BY MAGRATHEA.
## This file was automatically generated and changes can be overwritten through the admin
## -- date of creation: [2023-08-25 22:17:36]

namespace MagratheaContacts\Email;

use Magrathea2\iMagratheaModel;
use Magrathea2\MagratheaModel;

class EmailBase extends MagratheaModel implements iMagratheaModel {

	public $id, $source_id, $origin_key, $email_from, $email_replyTo, $email_to, $msg_subject, $message, $priority, $add_date, $sent_date, $sent_status;
	public $created_at, $updated_at;
	protected $autoload = array("Source" => ["obj" => "\MagratheaContacts\Source\Source","field" => "source_id"]);
	public $Source;

	public function __construct(  $id=0  ){ 
		$this->MagratheaStart();
		if( !empty($id) ){
			$pk = $this->dbPk;
			$this->$pk = $id;
			$this->GetById($id);
		}
	}
	public function MagratheaStart(){
		$this->dbTable = "mail";
		$this->dbPk = "id";
		$this->dbValues["id"] = "int";
		$this->dbValues["source_id"] = "int";
		$this->dbValues["origin_key"] = "string";
		$this->dbValues["email_from"] = "string";
		$this->dbAlias["from"] = "email_from";
		$this->dbValues["email_replyTo"] = "string";
		$this->dbAlias["replyTo"] = "email_replyTo";
		$this->dbValues["email_to"] = "string";
		$this->dbAlias["to"] = "email_to";
		$this->dbValues["msg_subject"] = "string";
		$this->dbAlias["subject"] = "msg_subject";
		$this->dbValues["message"] = "text";
		$this->dbValues["priority"] = "int";
		$this->dbValues["add_date"] = "datetime";
		$this->dbValues["sent_date"] = "datetime";
		$this->dbValues["sent_status"] = "int";

		$this->relations["properties"]["Source"] = null;
		$this->relations["methods"]["Source"] = "GetSource";
		$this->relations["lazyload"]["Source"] = "true";
		$this->dbValues["created_at"] =  "datetime";
		$this->dbValues["updated_at"] =  "datetime";

	}

	// >>> relations:
	public function GetSource(){
		if($this->relations["properties"]["Source"] != null) return $this->relations["properties"]["Source"];
		$this->relations["properties"]["Source"] = new \MagratheaContacts\Source\Source($this->source_id);
		return $this->relations["properties"]["Source"];
	}
	public function SetSource($source){
		$this->relations["properties"]["Source"] = $source;
		$this->source_id = $source->GetID();
		return $this;
	}

}
