<?php
## FILE GENERATED BY MAGRATHEA.
## This file was automatically generated and changes can be overwritten through the admin
## -- date of creation: [2023-08-11 12:11:56]

namespace MagratheaContacts\Email;

use Magrathea2\MagratheaModelControl;

class EmailControlBase extends MagratheaModelControl {
	protected static $modelNamespace = "MagratheaContacts\Email";
	protected static $modelName = "Email";
	protected static $dbTable = "mail";
}
